export const provinceDict: Record<string, string[]> = {
  "An Giang": [
    "Thoại Sơn",
    "Long Xuyên",
    "Phú Tân",
    "Tân Châu",
    "Châu Phú",
    "Chợ Mới",
    "Châu Đốc",
    "Tịnh Biên",
    "Châu Thành",
    "Tri Tôn",
  ],
  "Bà Rịa Vũng Tàu": [
    "Bà Rịa",
    "Châu Đức",
    "Long Điền",
    "Long Đất",
    "Phú Mỹ",
    "Vũng Tàu",
    "Xuyên Mộc",
    "Côn Đảo",
  ],
  "Bình Dương": [
    "Bàu Bàng",
    "Bắc Tân Uyên",
    "Bến Cát",
    "Dĩ An",
    "Dầu Tiếng",
    "Phú Giáo",
    "Thuận An",
    "Thủ Dầu Một",
    "Tân Uyên",
  ],
  "Bình Phước": [
    "Bình Long",
    "Bù Gia Mập",
    "Bù Đăng",
    "Bù Đốp",
    "Chơn Thành",
    "Lộc Ninh",
    "Phú Riềng",
    "Đồng Phú",
    "Đồng Xoài",
    "Hớn Quản",
    "Phước Long",
  ],
  "Bình Thuận": [
    "Bắc Bình",
    "Hàm Thuận Bắc",
    "Hàm Thuận Nam",
    "Hàm Tân",
    "Phan Thiết",
    "Đảo Phú Quý",
    "Tuy Phong",
    "La Gi",
    "Tánh Linh",
    "Đức Linh",
  ],
  "Bình Định": [
    "Phù Cát",
    "Quy Nhơn",
    "Tuy Phước",
    "Vân Canh",
    "An Nhơn",
    "Hoài Nhơn",
    "Phù Mỹ",
    "Tây Sơn",
  ],
  "Bạc Liêu": [
    "Bạc Liêu",
    "Hòa Bình",
    "Giá Rai",
    "Phước Long",
    "Đông Hải",
    "Hồng Dân",
  ],
  "Bắc Giang": [
    "Bắc Giang",
    "Hiệp Hòa",
    "Lạng Giang",
    "Lục Nam",
    "Tân Yên",
    "Việt Yên",
    "Yên Dũng",
    "Lục Ngạn",
    "Yên Thế",
    "Sơn Động",
  ],
  "Bắc Kạn": ["Bắc Kạn", "Chợ Mới", "Chợ Đồn", "Ba Bể"],
  "Bắc Ninh": [
    "Bắc Ninh",
    "Gia Bình",
    "Lương Tài",
    "Quế Võ",
    "Thuận Thành",
    "Tiên Du",
    "Từ Sơn",
    "Yên Phong",
  ],
  "Bến Tre": [
    "Bến Tre",
    "Châu Thành",
    "Ba Tri",
    "Mỏ Cày Nam",
    "Bình Đại",
    "Thạnh Phú",
    "Mỏ Cày Bắc",
    "Chợ Lách",
  ],
  "Cao Bằng": ["Cao Bằng", "Trà Lĩnh"],
  "Cà Mau": [
    "Cà Mau",
    "Cái Nước",
    "Năm Căn",
    "Trần Văn Thời",
    "U Minh",
    "Đầm Dơi",
    "Phú Tân",
  ],
  "Cần Thơ": [
    "Bình Thủy",
    "Cái Răng",
    "Ninh Kiều",
    "Phong Điền",
    "Ô Môn",
    "Thốt Nốt",
    "Thới Lai",
    "Vĩnh Thạnh",
    "Cờ Đỏ",
  ],
  "Gia Lai": [
    "Ia Grai",
    "Plei Ku",
    "ChưPRông",
    "KBang",
    "Chư Păh",
    "Chư Sê",
    "Đăk Đoa",
    "An Khê",
    "Chư Pưh",
    "Mang Yang",
    "Krông Pa",
    "Kông Chro",
    "Ia Pa",
    "Đăk Pơ",
  ],
  "Hà Giang": ["Hà Giang", "Bắc Quang", "Hoàng Su Phì", "Đồng Văn", "Vị Xuyên"],
  "Hà Nam": [
    "Duy Tiên",
    "Kim Bảng",
    "Phủ Lý",
    "Thanh Liêm",
    "Bình Lục",
    "Lý Nhân",
  ],
  "Hà Nội": [
    "Ba Vì",
    "Ba Đình",
    "Bắc Từ Liêm",
    "Chương Mỹ",
    "Cầu Giấy",
    "Gia Lâm",
    "Hai Bà Trưng",
    "Hoài Đức",
    "Hoàn Kiếm",
    "Hoàng Mai",
    "Hà Đông",
    "Long Biên",
    "Mê Linh",
    "Mỹ Đức",
    "Nam Từ Liêm",
    "Phú Xuyên",
    "Phúc Thọ",
    "Quốc Oai",
    "Sóc Sơn",
    "Sơn Tây",
    "Thanh Oai",
    "Thanh Trì",
    "Thanh Xuân",
    "Thường Tín",
    "Thạch Thất",
    "Tây Hồ",
    "Đan Phượng",
    "Đông Anh",
    "Đống Đa",
    "Ứng Hòa",
  ],
  "Hà Tĩnh": [
    "Can Lộc",
    "Hà Tĩnh",
    "Kỳ Anh",
    "Nghi Xuân",
    "Cẩm Xuyên",
    "Thạch Hà",
    "Lộc Hà",
    "Hương Sơn",
    "Hương Khê",
    "Hồng Lĩnh",
    "Đức Thọ",
  ],
  "Hòa Bình": [
    "Cao Phong",
    "Hòa Bình",
    "Kim Bôi",
    "Lương Sơn",
    "Lạc Thủy",
    "Mai Châu",
    "Tân Lạc",
    "Yên Thủy",
    "Đà Bắc",
    "Lạc Sơn",
  ],
  "Hưng Yên": [
    "Hưng Yên",
    "Khoái Châu",
    "Kim Động",
    "Mỹ Hào",
    "Phù Cừ",
    "Tiên Lữ",
    "Văn Giang",
    "Văn Lâm",
    "Yên Mỹ",
    "Ân Thi",
  ],
  "Hải Dương": [
    "Chí Linh",
    "Gia Lộc",
    "Hải Dương",
    "Bình Giang",
    "Cẩm Giàng",
    "Kim Thành",
    "Nam Sách",
    "Thanh Hà",
    "Thanh Miện",
    "Tứ Kỳ",
    "Kinh Môn",
    "Ninh Giang",
  ],
  "Hải Phòng": [
    "An Dương",
    "An Lão",
    "Cát Hải",
    "Dương Kinh",
    "Hải An",
    "Hồng Bàng",
    "Kiến An",
    "Kiến Thụy",
    "Lê Chân",
    "Ngô Quyền",
    "Thủy Nguyên",
    "Vĩnh Bảo",
    "Đồ Sơn",
    "Tiên Lãng",
  ],
  "Hậu Giang": [
    "Châu Thành",
    "Ngã Bảy",
    "Vị Thanh",
    "Châu Thành A",
    "Phụng Hiệp",
    "Thị xã Long Mỹ",
    "Vị Thủy",
  ],
  "Hồ Chí Minh": [
    "Bình Chánh",
    "Bình Thạnh",
    "Bình Tân",
    "Cần Giờ",
    "Củ Chi",
    "Gò Vấp",
    "Hóc Môn",
    "Nhà Bè",
    "Phú Nhuận",
    "Quận 1",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Thủ Đức",
    "Tân Bình",
    "Tân Phú",
  ],
  "Khánh Hòa": [
    "Cam Lâm",
    "Cam Ranh",
    "Diên Khánh",
    "Khánh Vĩnh",
    "Nha Trang",
    "Ninh Hòa",
    "Vạn Ninh",
    "Trường Sa",
    "Khánh Sơn",
  ],
  "Kiên Giang": [
    "Châu Thành",
    "Phú Quốc",
    "Rạch Giá",
    "Hà Tiên",
    "Kiên Hải",
    "An Biên",
    "Kiên Lương",
    "Hòn Đất",
    "Giồng Riềng",
    "Gò Quao",
    "Giang Thành",
  ],
  "Kon Tum": [
    "Kon Rẫy",
    "Đăk Glei",
    "Đăk Hà",
    "Ngọc Hồi",
    "Kon Plông",
    "KonTum",
    "Sa Thầy",
  ],
  "Lai Châu": ["Tam Đường", "Lai Châu", "Phong Thổ"],
  "Long An": [
    "Bến Lức",
    "Châu Thành",
    "Cần Giuộc",
    "Cần Đước",
    "Thủ Thừa",
    "Tân An",
    "Tân Hưng",
    "Tân Trụ",
    "Đức Huệ",
    "Đức Hòa",
    "Kiến Tường",
    "Mộc Hóa",
    "Thạnh Hóa",
    "Vĩnh Hưng",
    "Tân Thạnh",
  ],
  "Lào Cai": ["Sa Pa", "Lào Cai", "Bảo Thắng", "Bát Xát"],
  "Lâm Đồng": [
    "Bảo Lâm",
    "Bảo Lộc",
    "Di Linh",
    "Lâm Hà",
    "Lạc Dương",
    "Đam Rông",
    "Đà Lạt",
    "Đức Trọng",
    "Đạ Huoai",
    "Đơn Dương",
    "Đạ Tẻh",
    "Cát Tiên",
  ],
  "Lạng Sơn": ["Cao Lộc", "Lạng Sơn", "Hữu Lũng", "Bắc Sơn"],
  "Nam Định": [
    "Giao Thủy",
    "Hải Hậu",
    "Nam Định",
    "Mỹ Lộc",
    "Vụ Bản",
    "Xuân Trường",
    "Nghĩa Hưng",
    "Ý Yên",
    "Nam Trực",
    "Trực Ninh",
  ],
  "Nghệ An": [
    "Yên Thành",
    "Vinh",
    "Quỳnh Lưu",
    "Cửa Lò",
    "Diễn Châu",
    "Nam Đàn",
    "Nghĩa Đàn",
    "Hoàng Mai",
    "Đô Lương",
    "Nghi Lộc",
    "Thái Hòa",
    "Hưng Nguyên",
    "Anh Sơn",
  ],
  "Ninh Bình": [
    "Ninh Bình",
    "Gia Viễn",
    "Hoa Lư",
    "Nho Quan",
    "Yên Mô",
    "Tam Điệp",
    "Yên Khánh",
    "Kim Sơn",
  ],
  "Ninh Thuận": [
    "Ninh Hải",
    "Ninh Phước",
    "Phan Rang - Tháp Chàm",
    "Thuận Nam",
    "Ninh Sơn",
    "Bác Ái",
    "Thuận Bắc",
  ],
  "Phú Thọ": [
    "Cẩm Khê",
    "Lâm Thao",
    "Phú Thọ",
    "Tam Nông",
    "Thanh Ba",
    "Thanh Sơn",
    "Thanh Thủy",
    "Việt Trì",
    "Phù Ninh",
    "Tân Sơn",
    "Yên Lập",
    "Đoan Hùng",
    "Hạ Hòa",
  ],
  "Phú Yên": [
    "Tuy Hòa",
    "Đông Hòa",
    "Sông Cầu",
    "Phú Hòa",
    "Sơn Hòa",
    "Tuy An",
    "Sông Hinh",
    "Đồng Xuân",
  ],
  "Quảng Bình": [
    "Quảng Ninh",
    "Đồng Hới",
    "Ba Đồn",
    "Tuyên Hóa",
    "Bố Trạch",
    "Lệ Thủy",
    "Quảng Trạch",
    "Minh Hóa",
  ],
  "Quảng Nam": [
    "Nông Sơn",
    "Duy Xuyên",
    "Hội An",
    "Núi Thành",
    "Thăng Bình",
    "Điện Bàn",
    "Đông Giang",
    "Đại Lộc",
    "Phú Ninh",
    "Quế Sơn",
    "Tam Kỳ",
    "Bắc Trà My",
    "Tiên Phước",
    "Nam Giang",
  ],
  "Quảng Ngãi": [
    "Lý Sơn",
    "Quảng Ngãi",
    "Sơn Tịnh",
    "Tư Nghĩa",
    "Bình Sơn",
    "Mộ Đức",
    "Đức Phổ",
    "Ba Tơ",
    "Nghĩa Hành",
  ],
  "Quảng Ninh": [
    "Cẩm Phả",
    "Hạ Long",
    "Móng Cái",
    "Quảng Yên",
    "Vân Đồn",
    "Hải Hà",
    "Uông Bí",
    "Đông Triều",
    "Cô Tô",
    "Đầm Hà",
    "Tiên Yên",
  ],
  "Quảng Trị": [
    "Gio Linh",
    "Hải Lăng",
    "Triệu Phong",
    "Vĩnh Linh",
    "Đông Hà",
    "Cam Lộ",
    "Quảng Trị",
  ],
  "Sóc Trăng": [
    "Mỹ Tú",
    "Trần Đề",
    "Mỹ Xuyên",
    "Sóc Trăng",
    "Thạnh Trị",
    "Ngã Năm",
    "Kế Sách",
    "Châu Thành",
    "Cù Lao Dung",
    "Long Phú",
  ],
  "Sơn La": ["Mộc Châu", "Bắc Yên", "Sơn La", "Vân Hồ", "Phù Yên", "Sốp Cộp"],
  "Thanh Hóa": [
    "Hoằng Hóa",
    "Nga Sơn",
    "Nghi Sơn",
    "Ngọc Lặc",
    "Nông Cống",
    "Sầm Sơn",
    "Thanh Hóa",
    "Thạch Thành",
    "Triệu Sơn",
    "Đông Sơn",
    "Bỉm Sơn",
    "Hà Trung",
    "Bá Thước",
    "Như Thanh",
    "Như Xuân",
    "Quảng Xương",
    "Thọ Xuân",
    "Yên Định",
    "Cẩm Thủy",
    "Hậu Lộc",
    "Lang Chánh",
    "Vĩnh Lộc",
    "Thiệu Hóa",
    "Thường Xuân",
  ],
  "Thái Bình": [
    "Hưng Hà",
    "Kiến Xương",
    "Thái Bình",
    "Vũ Thư",
    "Đông Hưng",
    "Tiền Hải",
    "Quỳnh Phụ",
    "Thái Thuỵ",
  ],
  "Thái Nguyên": [
    "Phổ Yên",
    "Sông Công",
    "Thái Nguyên",
    "Phú Bình",
    "Đại Từ",
    "Phú Lương",
    "Võ Nhai",
    "Đồng Hỷ",
  ],
  "Thừa Thiên Huế": [
    "Huế",
    "Hương Thủy",
    "Phong Điền",
    "Phú Lộc",
    "Phú Vang",
    "Hương Trà",
    "Quảng Điền",
    "A Lưới",
  ],
  "Tiền Giang": [
    "Châu Thành",
    "Cái Bè",
    "Gò Công",
    "Gò Công Tây",
    "Gò Công Đông",
    "Mỹ Tho",
    "Tân Phước",
    "Cai Lậy",
    "Chợ Gạo",
    "Tân Phú Đông",
    "Huyện Cai Lậy",
  ],
  "Trà Vinh": [
    "Trà Vinh",
    "Càng Long",
    "Trà Cú",
    "Tiểu Cần",
    "Duyên Hải",
    "Châu Thành",
    "Cầu Ngang",
  ],
  "Tuyên Quang": ["Tuyên Quang", "Yên Sơn", "Sơn Dương"],
  "Tây Ninh": [
    "Châu Thành",
    "Dương Minh Châu",
    "Gò Dầu",
    "Hòa Thành",
    "Trảng Bàng",
    "Tân Biên",
    "Tân Châu",
    "Tây Ninh",
    "Bến Cầu",
  ],
  "Vĩnh Long": [
    "Bình Minh",
    "Tam Bình",
    "Bình Tân",
    "Vĩnh Long",
    "Long Hồ",
    "Mang Thít",
    "Vũng Liêm",
    "Trà Ôn",
  ],
  "Vĩnh Phúc": [
    "Bình Xuyên",
    "Lập Thạch",
    "Phúc Yên",
    "Tam Dương",
    "Tam Đảo",
    "Vĩnh Yên",
    "Vĩnh Tường",
    "Yên Lạc",
    "Sông Lô",
  ],
  "Yên Bái": [
    "Yên Bái",
    "Trấn Yên",
    "Văn Yên",
    "Yên Bình",
    "Nghĩa Lộ",
    "Mù Cang Chải",
    "Lục Yên",
    "Văn Chấn",
  ],
  "Điện Biên": ["Mường Nhé", "Điện Biên", "Điện Biên Phủ"],
  "Đà Nẵng": [
    "Cẩm Lệ",
    "Hòa Vang",
    "Hải Châu",
    "Liên Chiểu",
    "Ngũ Hành Sơn",
    "Sơn Trà",
    "Thanh Khê",
  ],
  "Đắk Lắk": [
    "Buôn Hồ",
    "Buôn Ma Thuột",
    "Buôn Đôn",
    "Cư Kuin",
    "Cư M'gar",
    "Krông Năng",
    "Lăk",
    "Ea Kar",
    "M'Đrăk",
    "Krông Ana",
    "Krông Buk",
    "Krông Pắc",
    "Ea H'Leo",
    "Ea Súp",
    "Krông Bông",
  ],
  "Đắk Nông": [
    "Dăk GLong",
    "Dăk R'Lấp",
    "Dăk Song",
    "Gia Nghĩa",
    "Cư Jút",
    "Dăk Mil",
    "Krông Nô",
    "Tuy Đức",
  ],
  "Đồng Nai": [
    "Biên Hòa",
    "Cẩm Mỹ",
    "Long Khánh",
    "Long Thành",
    "Nhơn Trạch",
    "Thống Nhất",
    "Trảng Bom",
    "Vĩnh Cửu",
    "Xuân Lộc",
    "Định Quán",
    "Tân Phú",
  ],
  "Đồng Tháp": [
    "Lai Vung",
    "Cao Lãnh",
    "Sa Đéc",
    "Tháp Mười",
    "Huyện Cao Lãnh",
    "Lấp Vò",
    "Châu Thành",
    "Hồng Ngự",
    "Tam Nông",
    "Thanh Bình",
    "Tân Hồng",
  ],
};
